{% set version = "0.7" %}

package:
  name: otwrapy
  version: {{ version }}

source:
  fn: otwrapy-{{ version }}.tar.gz
  url: https://github.com/openturns/otwrapy/archive/v{{ version }}.tar.gz
  sha256: f72facf23074bc6aabae62f74e7162b69655ee1542721399e8a740fb24effcc1

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - numpy
    - openturns
  run:
    - python
    - numpy
    - joblib >=0.9.3
    - ipyparallel >=5.0.1
    - pathos >=0.2.0
    - openturns

test:
  imports:
    - otwrapy

about:
  home: https://github.com/openturns/otwrapy
  license: LGPL3
  license_file: LICENSE
  summary: General purpose OpenTURNS python wrapper tools

extra:
  recipe-maintainers:
    - jschueller
    - felipeam86
