# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UOzgDoyq+XOcqMjHWFW1fGgd/8Sk1wvUp18YzVfUAT2cLAgKeS0f8MqbU2jDUdUmFqMl3tYeNE/4ubui1Q7Yqnrco6rB5bfuD+jV+zu9JMaBnieaUfZIlaIW9LYE9hVPeoiuJ2ue4hUss5NdkDRdjX5mHYh3SEBkkMS+iYxqArnGUrtl24GMoBqE6WyhOv/waeCmz0ETZaPmeG6A8Len6A2be6L7LM5S9QbZSY7fR9Qek2+fImna/CS1LjfVIrud+BuhFkCPfl/swY/U/WDddAus7h+npo1D9RyQEXbz8gFAdriyACv/XZDNlxoxQ3jMm0SSgdUT4TOHWXyBN6JvdauWOxcsA15McPcci3UDgBAXkJCGOrPNJOZbzsZTyeC0/NNOfw7DYDUf+mJ+FsJBxZuggRRDHIhuAeXRlb7QnzaJxtR2kuuCo925FVEV49xZPBrrLvbNXsqGXKShH14GMumZQmE3RkJ0990m5aEYqozjxTtphUwQoDZCA9WOqNTAcA/a7Tip4Cuk1/HP0XGwhAwJ2c8N0K29UIHCuOTx9thE+LxsLaRM9FcK3X99IQlLgBgEGhaJW9I+/RHfU77eDSZOuDxctdoG0tKUXP/LuCDgOqqaa9payyl+pcSDx1KC829MFHvOGxOFR+wQlMqmE5hybaqqsr8AEsm2XmKZ+5s="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
